FROM centos

RUN yum install -y java

VOLUME /tmp
ADD ./spring-boot-web-0.0.1-SNAPSHOT.jar myapp.jar

#Updates the date for cache and stuff.
RUN sh -c 'touch /myapp.jar'

#-D param is to start tomcat faster
# ENTRYPOINT will run once the container is started.
# now run docker build -t spring-boot-docker . -t is for tag.
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/myapp.jar"]